### PR TITLE
Add more metadata to the simulation output headers.

### PR DESCRIPTION
**Pull request by schlafly**
This PR fills out a bit more of the simulation metadata to make it easier for users to find things.

It also fixes one bug where Poisson noise was being applied twice.

### CODE REVIEW

**Comment by schlafly** [comment]
@PaulHuwe, have you seen this kind of fits_embed failure before?  I'm embarrassed that I don't actually understand test-xdist vs. test-devdeps.

**Comment by PaulHuwe** [comment]
Yes - devdops is testing against the latest dev versions of dependencies listed in `requirements-dev.txt` - which has some significant changes. (I have run into these and started changing code for them in implementing RDM support.) That's why you are getting these errors.

**Comment by schlafly** [comment]
Should I ignore these for the purposes of deciding whether to merge?

**Comment by schlafly** [comment]
@PaulHuwe , is it okay for me to merge this?  Unfortunately it does touch the metadata and will probably cause some merge headaches.

**Comment by PaulHuwe** [comment]
Yes, I will fix them all in my PR.

**Review by PaulHuwe — APPROVED** [review]
LGTM with the proviso that I will be modifying this a bit in my PR.

**Pull request merged**
