### PR TITLE
Implement classical non-linearity

### PR DESCRIPTION
**Pull request by schlafly**
This adds a new module that handles classical non-linearity.

There's some complexity needed to handle both images that already include poisson noise (e.g., from galsim's photon shooting rendering approach) and non-linearity.  That took a while to get right but ends up not being very expensive.  There is documentation in the l1 documentation and modules.

Also fix a bug in the updated exception logic in GWCS._xy that was preventing any images from being made when using CRDS.

### CODE REVIEW

**Comment by schlafly** [comment]
@PaulHuwe , @zacharyburnett , I added W503 to the flake8 ignore section because I couldn't figure out how to deal with not being allowed to break a line before (W503) or after (W504) a binary operator.  If this is too repulsive please let me know what is appropriate.

**Comment by zacharyburnett** [comment]
I think these errors can be solved by adding `build` to the `norecursedirs` list in `pyproject.toml`

**Comment by schlafly** [comment]
@PaulHuwe , I'm failing lots of tests but I don't really understand; our tests don't cover anything and I didn't consciously make any changes that touch any tests?

**Comment by zacharyburnett** [comment]
@schlafly yes it appears that `pytest` discovery is getting confused by the `build` directory, so you should add it to the `norecursedirs`

**Comment by schlafly** [comment]
@zacharyburnett , it looks like this builds now, and I'll go ahead and merge.  Thanks.  The code coverage reports that I've increased coverage by 19%, despite not touching any tests or doing anything.  That feels broken?

**Comment by zacharyburnett** [comment]
> @zacharyburnett , it looks like this builds now, and I'll go ahead and merge. Thanks. The code coverage reports that I've increased coverage by 19%, despite not touching any tests or doing anything. That feels broken?

yes that is strange, the coverage was 1% and now is 20%. However I can't see any actual issues with the tests themselves, and the coverage modules seems to be working fine from what I can see in the report

**Comment by PaulHuwe** [comment]
> @PaulHuwe , @zacharyburnett , I added W503 to the flake8 ignore section because I couldn't figure out how to deal with not being allowed to break a line before (W503) or after (W504) a binary operator. If this is too repulsive please let me know what is appropriate.

- I fixed lots of these in my tickets. I am not religious about this particular warning.

**Comment by PaulHuwe** [comment]
> > @zacharyburnett , it looks like this builds now, and I'll go ahead and merge. Thanks. The code coverage reports that I've increased coverage by 19%, despite not touching any tests or doing anything. That feels broken?
> 
> yes that is strange, the coverage was 1% and now is 20%. However I can't see any actual issues with the tests themselves, and the coverage modules seems to be working fine from what I can see in the report

This appears to be oddly common? I have seen it several times over several projects, but never investigated it further.

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Pull request merged**
