### PR TITLE
Miscellaneous fixes following initial science validation comments.

### PR DESCRIPTION
**Pull request by schlafly**
This PR makes a few changes following RTB comments.

I have added an additional sentence describing how maggies are converted into photons to the bandpass page at readthedocs.

The romanisim truncation support was half-baked and didn't propagate through to the places it needed to; this has been fixed.

### CODE REVIEW

**Comment by schlafly** [comment]
@AndreaBellini, I think this addresses your requested doc change.

@ojustino, thanks for noticing the issue with the read_pattern not being correctly propagated through in the truncated case.  Please see if this addresses your issue.

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Comment by ojustino** [comment]
Hi @schlafly, no problem, and thanks for making these fixes. The `read_pattern`-related additions make sense to me, and a quick check with my validation code now shows truncation working as intended.

**Comment by schlafly** [comment]
Thanks Justin.  @AndreaBellini, if the addition to the bandpass docs here
https://romanisim--131.org.readthedocs.build/en/131/romanisim/bandpass.html
addresses your concerns, I'll go ahead and merge this.

**Comment by AndreaBellini** [comment]
Hi Eddie,

I’m currently on travel with (at the mint) intermittent internet connection. Thanks for adding extra information. The text mentions photons, but there is no mention of DN and DN/s, which are the units in L1 and L2 data. Unless I missed it, the text does not tell the user how to convert from DN/s to AB mag.

Cheers,

Andrea

---
Dr. Andrea Bellini
Space Telescope Science Institute
3700 San Martin Drive
Baltimore MD 21210
Tel: +1 410 338 4431


On Jul 11, 2024, at 17:08, Eddie Schlafly ***@***.***> wrote:

﻿

Thanks Justin. @AndreaBellini<https://urldefense.com/v3/__https://github.com/AndreaBellini__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!00UYy-MDIBvWqZ-DRtJ9ERoMZxkepcTviClwHeRFp55MnxXX5YSqUaAjUzvkhQnG1P2hrVX0e5rZ_kB7R2gDo6Dz$>, if the addition to the bandpass docs here
https://romanisim--131.org.readthedocs.build/en/131/romanisim/bandpass.html<https://urldefense.com/v3/__https://romanisim--131.org.readthedocs.build/en/131/romanisim/bandpass.html__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!00UYy-MDIBvWqZ-DRtJ9ERoMZxkepcTviClwHeRFp55MnxXX5YSqUaAjUzvkhQnG1P2hrVX0e5rZ_kB7R8w0eEEP$>
addresses your concerns, I'll go ahead and merge this.

**Comment by schlafly** [comment]
Thanks Andrea.  I've now added a section to the L1 page that has the conversion from photons to DN via the gain.
https://romanisim--131.org.readthedocs.build/en/131/romanisim/l1.html#gain

**Comment by AndreaBellini** [comment]
Hi Eddie, please double check what is currently meant by “photons” then. The gain is only used to convert electrons to DNs. Are you sure you mean photons and not electrons?

If you really mean photons, then there is a further conversion factor that depends on the wavelength of the photons for shortish wavelengths. I think I read somewhere that the average for Roman is 4,7 electrons per photons, but I might be wrong.

Cheers,

Andrea

---
Dr. Andrea Bellini
Space Telescope Science Institute
3700 San Martin Drive
Baltimore MD 21210
Tel: +1 410 338 4431


On Jul 11, 2024, at 20:33, Eddie Schlafly ***@***.***> wrote:

﻿

Thanks Andrea. I've now added a section to the L1 page that has the conversion from photons to DN via the gain.
https://romanisim--131.org.readthedocs.build/en/131/romanisim/l1.html#gain<https://urldefense.com/v3/__https://romanisim--131.org.readthedocs.build/en/131/romanisim/l1.html*gain__;Iw!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2Ryk7W9oWQX7d0q3UJGtHXKqlXVicbBswv-rLMupG5eKcDXAzNGyKWqf_oFhJWMBxwZFr_YByTL_SeLKCxUjPImV$>

**Comment by schlafly** [comment]
This paper finds quantum yields peaking at 1.05 at 550 nm, with an average in the F062 band of probably around 1.03.
https://iopscience.iop.org/article/10.1088/1538-3873/ac46ba#paspac46baf7
In other bands they find ~1.003%.  That's certainly an effect I'm neglecting, assuming a quantum yield of 1.  The fact that the quantum yields are not exactly one means to me that there's some ~imprecision in the notion of gain and ramp fitting; when we pretend that the electrons are Poisson distributed, in fact they have some slightly more complex distribution.  It doesn't seem to me that this is an effect that we should be simulating at this stage---we certainly don't have requirements about modeling quantum yields, etc..

Is this in fact the effect you're concerned about here?

**Comment by AndreaBellini** [comment]
Hi Eddie,

I’m ok if you assume 1 photon = 1 electron if it is supported in the literature. Just add this information in the documentation and, as far as I am concerned, go ahead and merge the pull request.

Thank you for adding all of this into the documentation. Roman I-Sim will certainly benefit from it.

Cheers,

Andrea


---
Dr. Andrea Bellini
Space Telescope Science Institute
3700 San Martin Drive
Baltimore MD 21210
Tel: +1 410 338 4431


On Jul 12, 2024, at 18:07, Eddie Schlafly ***@***.***> wrote:

﻿

This paper finds quantum yields peaking at 1.05 at 550 nm, with an average in the F062 band of probably around 1.03.
https://iopscience.iop.org/article/10.1088/1538-3873/ac46ba#paspac46baf7<https://urldefense.com/v3/__https://iopscience.iop.org/article/10.1088/1538-3873/ac46ba*paspac46baf7__;Iw!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!3zr0xbnNEUUFtFbNkRnA0QiC0DRyeyUYrZY7y4nQ5NNNfMdKhXvP33gHfKXHyuketJ69ePanMZrpJQJ6_sms4TJm$>
In other bands they find ~1.003%. That's certainly an effect I'm neglecting, assuming a quantum yield of 1. The fact that the quantum yields are not exactly one means to me that there's some ~imprecision in the notion of gain and ramp fitting; when we pretend that the electrons are Poisson distributed, in fact they have some slightly more complex distribution. It doesn't seem to me that this is an effect that we should be simulating at this stage---we certainly don't have requirements about modeling quantum yields, etc..

Is this in fact the effect you're concerned about here?

**Pull request merged**
