### PR TITLE
[SCSB-174] move DMS requirement <-> test correlations from `@metrics_logger` decorators to `romanisim/tests/dms_requirement_tests.json`

### PR DESCRIPTION
**Pull request by zacharyburnett**
Resolves [SCSB-174](https://jira.stsci.edu/browse/SCSB-174)

consolidates all test requirement correlations into `romanisim/tests/dms_requirement_tests.json`, obviating the need to insert log messages at test execution time with `metrics_logger`

This PR (and its sister PRs https://github.com/spacetelescope/romancal/pull/1399 and https://github.com/spacetelescope/crds/pull/1064) blocks https://grit.stsci.edu/dmd/roman-metrics/-/merge_requests/21

### CODE REVIEW

**Review by jglorioso-stsci — APPROVED** [review]
Curious what the addition of romanisim/ramp_fit_casertano.c is?

Otherwise, looks good.

**Comment by zacharyburnett** [comment]
> Curious what the addition of romanisim/ramp_fit_casertano.c is?

oh good catch! I should add that to `.gitignore`

**Comment by schlafly** [comment]
Thanks, looks good to me.  One question: the new test_dms_requirements test aims to be a consistency check that the tests I've indicated should exist in the requirements.json file actually exist---correct?  If I deleted that file we might have issues in the future if I made a typo in the json file but it's not technically needed for the metrics code or for romanisim to work?

**Comment by zacharyburnett** [comment]
> Thanks, looks good to me. One question: the new test_dms_requirements test aims to be a consistency check that the tests I've indicated should exist in the requirements.json file actually exist---correct? If I deleted that file we might have issues in the future if I made a typo in the json file but it's not technically needed for the metrics code or for romanisim to work?

Correct, it's just a check to flag name changes or restructuring of tests to make sure the JSON file stays up-to-date

**Review by schlafly — APPROVED** [review]

**Pull request merged**
