### PR TITLE
[CI] install `fftw` with `brew`

### PR DESCRIPTION
**Pull request by zacharyburnett**

### CODE REVIEW

**Comment by zacharyburnett** [comment]
although `fftw` is installed with `brew`:
https://github.com/spacetelescope/romanisim/actions/runs/8912295254/job/24475468572?pr=116#step:4:257
```
==> Installing fftw
==> Pouring fftw--3.3.10_1.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/fftw/3.3.10_1: 73 files, 8.3MB
```

`pip` can't find `fftw`:
https://github.com/spacetelescope/romanisim/actions/runs/8912295254/job/24475468572?pr=116#step:10:43
```
      Looking for  libfftw3.dylib
      Could not find fftw3 library.  Make sure it is installed either in a standard
      location such as /usr/local/lib, or the installation directory is either in
      your LIBRARY_PATH or FFTW_DIR environment variable.
      error:
```

**Comment by zacharyburnett** [comment]
it appears I'll have to set `FFTW_DIR` with `setenv: |`; I'll look for where `brew` installs `fftw` to on macOS

**Comment by zacharyburnett** [comment]
for some reason it still fails:
https://github.com/spacetelescope/romanisim/actions/runs/8912757216/job/24476877098#step:10:587
```
      ld: library 'fftw3' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang++' failed with exit code 1
```

**Comment by schlafly** [comment]
I don't know anything about brew, but presumably it's putting libfftw3.dylib somewhere other than /usr/local/lib?  The only relevant log message I see from the installation is
https://github.com/spacetelescope/romanisim/actions/runs/8912757216/job/24476877098#step:4:263
but that may be a red herring.

**Comment by schlafly** [comment]
It doesn't seem likely to be relevant, but the only other hint from the GalSim installation is:
https://github.com/GalSim-developers/GalSim/blob/releases/2.5/.travis.yml#L126

**Comment by zacharyburnett** [comment]
when I install with `brew` on my local machine, it appears to automatically link to `/usr/local/lib/`: 
```
❯ ls /usr/local/lib/libfftw3*
/usr/local/lib/libfftw3.3.dylib			/usr/local/lib/libfftw3f_omp.3.dylib
/usr/local/lib/libfftw3.a			/usr/local/lib/libfftw3f_omp.a
/usr/local/lib/libfftw3.dylib			/usr/local/lib/libfftw3f_omp.dylib
/usr/local/lib/libfftw3_mpi.3.dylib		/usr/local/lib/libfftw3f_threads.3.dylib
/usr/local/lib/libfftw3_mpi.a			/usr/local/lib/libfftw3f_threads.a
/usr/local/lib/libfftw3_mpi.dylib		/usr/local/lib/libfftw3f_threads.dylib
/usr/local/lib/libfftw3_omp.3.dylib		/usr/local/lib/libfftw3l.3.dylib
/usr/local/lib/libfftw3_omp.a			/usr/local/lib/libfftw3l.a
/usr/local/lib/libfftw3_omp.dylib		/usr/local/lib/libfftw3l.dylib
/usr/local/lib/libfftw3_threads.3.dylib		/usr/local/lib/libfftw3l_mpi.3.dylib
/usr/local/lib/libfftw3_threads.a		/usr/local/lib/libfftw3l_mpi.a
/usr/local/lib/libfftw3_threads.dylib		/usr/local/lib/libfftw3l_mpi.dylib
/usr/local/lib/libfftw3f.3.dylib		/usr/local/lib/libfftw3l_omp.3.dylib
/usr/local/lib/libfftw3f.a			/usr/local/lib/libfftw3l_omp.a
/usr/local/lib/libfftw3f.dylib			/usr/local/lib/libfftw3l_omp.dylib
/usr/local/lib/libfftw3f_mpi.3.dylib		/usr/local/lib/libfftw3l_threads.3.dylib
/usr/local/lib/libfftw3f_mpi.a			/usr/local/lib/libfftw3l_threads.a
/usr/local/lib/libfftw3f_mpi.dylib		/usr/local/lib/libfftw3l_threads.dylib
```
I'll test with a workflow

**Comment by zacharyburnett** [comment]
that worked!

**Comment by schlafly** [comment]
Bingo, thanks, merging!

**Pull request merged**
