### PR TITLE
abstract data download step into separate reusable workflow

### PR DESCRIPTION
**Pull request by zacharyburnett**
attempt to make WebbPSF data download / caching step simpler and more maintainable

### CODE REVIEW

**Comment by schlafly** [comment]
This was left as a draft and I ignored it; should we move forward here?

**Comment by zacharyburnett** [comment]
> This was left as a draft and I ignored it; should we move forward here?

I don't remember why I left it as a draft, but if it works and the tests pass then go ahead

**Comment by zacharyburnett** [comment]
oh wait, the tests DON'T pass, that must be why. I'll take a look

**Comment by schlafly** [comment]
I'm looking at some test failures in my unrelated PR, which is why I saw these again.  Maybe take another look tomorrow.

**Comment by zacharyburnett** [comment]
I still had to delete the cache manually, as a newer data version is out now. We could fix that automatically by periodically downloading the data and comparing the hash to the existing cache, or just continue deleting the cache every so often

**Comment by schlafly** [comment]
Looks good, merging!

**Pull request merged**
