### PR TITLE
Add Casertano+22 style ramp fitting to the simulator.

### PR DESCRIPTION
**Pull request by schlafly**
This is an initial implementation of the Casertano+22 ramp fitting algorithm in the simulator.

This is by and large a straightforward implementation directly following the paper.

Some minor choices made:
- I fit all subramps with >1 resultant and average them with inverse variance weights using the read noise variance contribution to the slopes.
- We use cython to do the loops over the different sized ramps; I couldn't figure out a good numpy non-loopy algorithm.

### CODE REVIEW

**Comment by schlafly** [comment]
@zacharyburnett , if you get a chance, can you take a quick look at this?  I'm trying to add a cython module to the package (romanisim/ramp_fit_casertano.pyx).  This builds fine for me locally when I do python setup.py build_ext, but it looks like I need to tell the CI stuff to do that as well, and I don't know where that invocation goes.

**Comment by zacharyburnett** [comment]
With PEP517 you (ideally) should not need to call `setup.py` directly, merely `pip install .`; does this, or alternatively `pip install -e .`, work to install the cython extensions?

**Comment by zacharyburnett** [comment]
@schlafly for testing purposes you could try adding `package: editable` to the `[testenv]` section in `tox.ini`; that will run `pip install -e .` and might install the C extensions correctly

**Comment by schlafly** [comment]
@zacharyburnett , it looks to me like pip install . does install the module?
i.e., I made a new environment, cloned the repo, checked out this branch, ran:
```
pip install .
ls /path/to/environment/lib/python3.11/site-packages/romanisim/
```
and I see ```ramp_fit_casertano.cpython-311-darwin.so``` in the results.  Presumably I'm not duplicating the CI environment well enough, but I haven't understood this yet.

**Comment by zacharyburnett** [comment]
> @zacharyburnett , it looks to me like pip install . does install the module? i.e., I made a new environment, cloned the repo, checked out this branch, ran:
> 
> ```
> pip install .
> ls /path/to/environment/lib/python3.11/site-packages/romanisim/
> ```
> 
> and I see `ramp_fit_casertano.cpython-311-darwin.so` in the results. Presumably I'm not duplicating the CI environment well enough, but I haven't understood this yet.

Does that also work when running tox, i.e. `tox -e test-xdist`? From what I remember, the way `tox` implements PEP517, it does not play nicely with C extensions for some reason. I think the workaround for now might just be to force `package: editable` in `tox.ini`

**Comment by schlafly** [comment]
@PaulHuwe , @stscieisenhamer , if you have any interest reviewing, please do.  I'll probably merge Monday.  This has the Casertano+ style ramp fitting and a new cython module implementing it.

**Pull request merged**
